version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tis193
      MYSQL_DATABASE: docker-rails-practice
      MYSQL_USER: azarashi
      MYSQL_PASSWORD: tis193
    ports:
      - "3306:3306"

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/hoge_project
    ports:
      - "8080:8080"

  web:
    container_name: practice_web
    build: .
    command: rails s -p 3000 -b '0.0.0.0' && bundle exec puma -C config/puma.rb
    volumes:
      - .:/practice
      - ./public:/practice/public
      - ./tmp:/practice/tmp
      - ./log:/practice/log
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    container_name: practice_nginx
    build: ./containers/nginx
    volumes:
      - ./public:/practice/public
      - ./tmp:/practice/tmp
    ports:
      - "80:80"
    depends_on:
      - web