version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: tis193
    working_directory: ~/circleci-rails-doing-log

    steps:
      - checkout

      - run: 
          name: Wait Docker container
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-
      - run: gem install bundler -v 2.0.1
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test